import type { Metadata } from 'next';
import './globals.css';
import { IconArrowRightToArc, IconLayout2Filled, IconUserPlus } from '@tabler/icons-react';
import Link from 'next/link';

import NavItem from '@/app/components/NavItem';

export const metadata: Metadata = {
    title: 'Luba Beats',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`h-full w-full bg-base-300`}>
                {/* <div className="w-full max-h-full bg-base-300">{children}</div> */}
                <div className="flex flex-col h-screen">
                    <div className="navbar bg-base-100 shadow-sm flex justify-between border-b-2 border-emerald-800">
                        <Link
                            href="/"
                            className="flex items-center btn btn-ghost text-xl rounded-2xl"
                        >
                            <span className="text-emerald-500 text-3xl text-shadow-[0_0_0px_#10b981,0_0_2px_#10b981,0_0_12px_#10b981]">
                                LUBA
                            </span>
                            <span>BEATS</span>
                        </Link>
                        <div className="flex gap-4 me-4">
                            <NavItem
                                href="/catalog"
                                icon={<IconLayout2Filled className="size-7" />}
                                text="Public Catalog"
                            />
                            <NavItem
                                href="/auth/signin"
                                icon={<IconArrowRightToArc className="size-7 me-1" />}
                                text="Sign In"
                            />
                            <NavItem
                                href="/auth/signup"
                                icon={<IconUserPlus className="size-7 me-1" />}
                                text="Sign Up"
                            />
                        </div>
                    </div>
                    <div className="flex-1 w-full overflow-y-auto bg-base-300 grid-scroll">
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
